[credentials]
usernames = [
    "jsmith",
    "rbriggs",
    "karine@cofrat.com.br"
]
passwords = [
    "senha123",
    "abc@123",
    "Geladeira123!"
]

[supabase]
url = "https://mytbufiwnfsphvimvvvu.supabase.co"
service_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15dGJ1Zml3bmZzcGh2aW12dnZ1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1Nzc4NDQ2NywiZXhwIjoyMDczMzYwNDY3fQ.tbe31KF4eWkotTs0sx-pXcCGEVwLrxfvd5Wd9WtSW-Q"
access_key_id = '2709775cce628ea71bf4f8753cc1509a'